name: Build and Push Update Automatically

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
    
jobs:
  build-win:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: Remove-Item -path .\dist\win-unpacked\ -recurse  # This will make sure that Build Artifact doesn't take a butt load of time to zip up the dist folder I need
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_IP }}
        port: 22
        removeExtraFiles: false
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/

  build-mac:

    runs-on: macOS-11

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: npm install
    - run: npm run build
    - run: sudo rm -R ./dist/mac/
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_IP }}
        port: 22
        removeExtraFiles: false
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/

  build-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: sudo rm -R ./dist/linux-unpacked/
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.SFTP_IP }}
        port: 22
        removeExtraFiles: false
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: ./dist/
        remoteDir: /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/

  release-update:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: sleep 550
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/* /usr/share/nginx/updates/falix-software/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/* /usr/share/nginx/updates/falix-software/
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/* /usr/share/nginx/updates/falix-software/
    
    - run: sudo rm /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/*.exe.blockmap
    - run: sudo rm /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/*.dmg.blockmap 
    
    - run: sudo mv /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/*.exe /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/FalixNodes-Desktop.exe
    - run: sudo mv /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/*.dmg /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/FalixNodes-Desktop.dmg
    - run: sudo mv /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/*.AppImage /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/FalixNodes-Desktop.AppImage
    
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/windows/FalixNodes-Desktop.exe /usr/share/nginx/cdn/files/downloads/falixnodes-desktop/FalixNodes-Desktop.exe
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/mac/FalixNodes-Desktop.dmg /usr/share/nginx/cdn/files/downloads/falixnodes-desktop/FalixNodes-Desktop.dmg
    - run: sudo cp /usr/share/nginx/updates/.prepare/falixnodes-desktop/linux/FalixNodes-Desktop.AppImage /usr/share/nginx/cdn/files/downloads/falixnodes-desktop/FalixNodes-Desktop.AppImage
